-- Users table
CREATE TABLE users(
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(64) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- photos
CREATE TABLE image(
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    filename VARCHAR(100) NOT NULL
);